// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGTsHlX2mBpOZxxKrCLgXX-5ZqQqvgyow',
    appId: '1:984771018295:web:cab3728ae57ce19f82c9b2',
    messagingSenderId: '984771018295',
    projectId: 'my-first-project-d2e46',
    authDomain: 'my-first-project-d2e46.firebaseapp.com',
    storageBucket: 'my-first-project-d2e46.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLKcluvhVMoykI3oYKRdYXAw5ar4oezTs',
    appId: '1:984771018295:android:c6c29ce99e5d776382c9b2',
    messagingSenderId: '984771018295',
    projectId: 'my-first-project-d2e46',
    storageBucket: 'my-first-project-d2e46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVgim2bHnQyH1S66i-kmsFiFlu6Dg0qGc',
    appId: '1:984771018295:ios:3eb3b93f97664e2182c9b2',
    messagingSenderId: '984771018295',
    projectId: 'my-first-project-d2e46',
    storageBucket: 'my-first-project-d2e46.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVgim2bHnQyH1S66i-kmsFiFlu6Dg0qGc',
    appId: '1:984771018295:ios:3eb3b93f97664e2182c9b2',
    messagingSenderId: '984771018295',
    projectId: 'my-first-project-d2e46',
    storageBucket: 'my-first-project-d2e46.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGTsHlX2mBpOZxxKrCLgXX-5ZqQqvgyow',
    appId: '1:984771018295:web:81ae2f24818f642182c9b2',
    messagingSenderId: '984771018295',
    projectId: 'my-first-project-d2e46',
    authDomain: 'my-first-project-d2e46.firebaseapp.com',
    storageBucket: 'my-first-project-d2e46.firebasestorage.app',
  );
}
